# Generated by Django 5.2.13 on 2026-05-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
